title: sfxworks
baseURL: 'https://sfxworks.net'
languageCode: "en-us"
theme: amperage

menu:
  main:
    - identifier: github
      name: GitHub
      url: 'https://github.com/sfxworks'
      weight: 10