title: sfxworks
baseURL: 'https://sfxworks.net'
languageCode: "en-us"
theme: amperage

menu:
  main:
    - identifier: github
      name: GitHub
      url: 'https://github.com/sfxworks'
      weight: 10
deployment:
  targets:
    name: sfxworks-s3
    URL: s3://sfxworks-7dfa7fa6-0f8a-4c09-b112-26c66c3e52e7?endpoint=rgw.sfxworks.net&disableSSL=false&s3ForcePathStyle=true
